### ISSUE TITLE
install node

### ISSUE THREAD

**Issue by UziTech** [Arcanemagus/atom-docker-ci#1]
some packages require node to be installed

https://github.com/AtomLinter/linter-coffeelint/pull/120

https://circleci.com/gh/AtomLinter/linter-coffeelint/279

**Comment by Arcanemagus** [comment]
On the rare project that actually needs it installed in the system, this is how I've done it:
[`linter-bootlint`](https://github.com/AtomLinter/linter-bootlint/blob/a467b2accce5bbb5c87693c9c90d1a7f6591e267/.circleci/config.yml#L11-L20)

I'm still debating on whether I want to create versions of this image with bundled runtimes as it would create quite a bit of noise in the tags to be able to specify "atom vx.y.z with ruby va.b.c".

Alternatively I could just bundle _every_ runtime used, but that would prevent users of the image from being able to use their own specific version of a run time (or at least require uninstalling the current version).

_Note: The linked issue actually has nothing to do with this, comment incoming there explaining it._

**Comment by UziTech** [comment]
You could make it so users could specify a version they want with an environment variable?
